default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  url: postgresql://postgres@localhost:5432

development:
  <<: *default
  database: glue-fm_development

test:
  <<: *default
  database: glue-fm_test

production:
  <<: *default
  database: glue-fm_production
  username: glue-fm
  password: <%= ENV['GLUE-FM_DATABASE_PASSWORD'] %>
